apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: ghcr.io/mochizuki875/ubuntu-debug:22.04
    name: ubuntu
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
